services:
  - type: web
    name: nirdist-backend
    env: java
    region: oregon
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean install -DskipTests
    startCommand: java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/nirdist-backend-1.0.0.jar
    envVars:
      - key: JWT_SECRET
        value: "51llV0Q+aMC2Rike4xj4evPsOk9RoXd91V2dQq1W4Zr0Eu5IlFM4tXK1oAt9hJYL3t1DTIDiBam7io6Hwgrleg=="
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: nirdist-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: nirdist-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nirdist-db
          property: password
    healthCheckPath: /api/health
    
databases:
  - name: nirdist-db
    databaseName: nirdist
    user: nirdist_user
    postgresMajorVersion: '15'
